name: riverpod_app
description: Riverpod learn Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1


environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.10.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

#  provider: ^6.0.2
#  image_picker: ^0.8.3+3
#  widgets: ^1.4.5
#  uni_links: ^0.5.1
#  logger: 1.1.0
#  charts_flutter: ^0.12.0
#  http: ^0.13.4

  freezed:
  shared_preferences: ^2.0.15
  webview_flutter:
  json_annotation:

  # Flavor # flutter run --dart-define=FLAVOR=dev
  flutter_flavorizr: ^2.1.3
  package_info_plus: ^1.4.2 # アプリ情報取得
  permission_handler: ^10.0.0 # 権限確認

  # Architecture
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.10

  # Firebase
  firebase_crashlytics: ^2.8.4
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  cloud_firestore: ^3.2.1
  flutter_slidable: ^1.3.0
  firebase_storage: ^10.3.1
  firebase_performance: ^0.7.1+2

  # Sign in
  google_sign_in: ^5.3.3
  sign_in_with_apple: ^4.0.0
  flutter_line_sdk: ^2.2.0

  # Network gateway
  dio: ^4.0.1
  dio_firebase_performance: ^0.3.1-dev.3
  retrofit: ^2.0.1
  # User-Agent Client Hints
  ua_client_hints: ^1.1.1

  # Model
  json_serializable: ^6.2.0
  freezed_annotation: ^0.15.0

  # DateTime
  intl: ^0.17.0

  # UIs
  gap: ^2.0.0
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3 # カメラ・フォトギャラリー
  cached_network_image: ^3.2.0 # ネットワークイメージ

  # Utils
  simple_logger: ^1.9.0 # ログ出力
  enum_to_string: ^2.0.1 # リストをenum化
  flutter_image_compress: ^1.1.0 # 画像の圧縮
  flutter_svg: ^0.23.0+1 # 画像拡張子を追加
  collection: ^1.15.0 # 万能型変換

dev_dependencies: # flutter packages pub run build_runner build
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable:
  freezed_annotation:
  freezed: ^0.15.0

  flutter_launcher_icons: ^0.9.2 # アプリアイコンの生成

  # For Networking
  retrofit_generator: ^2.0.0+1

  # For Assets
  flutter_gen_runner: ^4.0.1

  # For Navigation
  auto_route_generator: ^3.0.1


  # For Analyzer
  flutter_lints: ^1.0.4

  # For Testing
  mocktail: ^0.2.0
  mocktail_image_network: ^0.2.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons: # flutter pub run flutter_launcher_icons:main
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/debug/
    - assets/launcher_icon/


